//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 06:03:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ucll.be/java/ent/students")
package be.ucll.java.ent.soap.model.v1;
